# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vortech NZ
email: web@vortech.nz
description: > # this means to ignore newlines until "baseurl:"
  Vortech NZ - Unmanned Aerial Vehicles
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vortech-nz.github.io" # TODO: change this
twitter_username: vortech
github_username: vortech-nz

# Build settings
markdown: kramdown
